[2024-08-28T09:12:39.021+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T09:12:39.037+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:12:39.043+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:12:39.043+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-28T09:12:39.055+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): create_table> on 2024-08-26 00:00:00+00:00
[2024-08-28T09:12:39.061+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T09:12:39.062+0000] {standard_task_runner.py:72} INFO - Started process 1286 to run task
[2024-08-28T09:12:39.063+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_table', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmpnglt2icj']
[2024-08-28T09:12:39.063+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask create_table
[2024-08-28T09:12:39.103+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T09:12:39.171+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='asukhikh' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-28T09:12:39.172+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T09:12:39.172+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T09:12:39.173+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2024-08-28 09:12:39.037742+00:00
[2024-08-28T09:12:39.173+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T09:12:39.173+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T09:12:39.174+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS Orders (
                OrderID int,
                Status varchar(50)
            )
        
[2024-08-28T09:12:39.181+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:12:39.190+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:12:39.202+0000] {sql.py:509} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS Orders (
                OrderID int,
                Status varchar(50)
            )
        , parameters: None
[2024-08-28T09:12:39.217+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T09:12:39.218+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=create_table, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240828T091239, end_date=20240828T091239
[2024-08-28T09:12:39.228+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-28T09:12:39.228+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-28T09:12:39.228+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator queued_at:2024-08-28 09:11:22.301446+00:00
[2024-08-28T09:12:39.229+0000] {logging_mixin.py:190} INFO - Task hostname:2d2e6ae1efc8 operator:PostgresOperator
[2024-08-28T09:12:39.276+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T09:12:39.285+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T09:12:39.299+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-28T09:12:39.302+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-28T09:21:13.237+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T09:21:13.256+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:21:13.263+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:21:13.263+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-28T09:21:13.276+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): create_table> on 2024-08-26 00:00:00+00:00
[2024-08-28T09:21:13.286+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1451) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T09:21:13.287+0000] {standard_task_runner.py:72} INFO - Started process 1453 to run task
[2024-08-28T09:21:13.287+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_table', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmphfl1p_z2']
[2024-08-28T09:21:13.288+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask create_table
[2024-08-28T09:21:13.332+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T09:21:13.402+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='asukhikh' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-28T09:21:13.403+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T09:21:13.404+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T09:21:13.404+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2024-08-28 09:21:13.257075+00:00
[2024-08-28T09:21:13.405+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T09:21:13.405+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T09:21:13.405+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS Orders (
                OrderID int,
                Status varchar(50);
            )
        
[2024-08-28T09:21:13.415+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:21:13.442+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:21:13.725+0000] {sql.py:509} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS Orders (
                OrderID int,
                Status varchar(50);
            )
        , parameters: None
[2024-08-28T09:21:13.735+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near ";"
LINE 4:                 Status varchar(50);
                                          ^

[2024-08-28T09:21:13.767+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-28T09:21:13.768+0000] {logging_mixin.py:190} INFO - Task start:2024-08-28 09:21:13.257075+00:00 end:2024-08-28 09:21:13.766768+00:00 duration:0.509693
[2024-08-28T09:21:13.769+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): create_table> dag:<DAG: dag_with_postgres_operator> dagrun:<DagRun dag_with_postgres_operator @ 2024-08-26 00:00:00+00:00: scheduled__2024-08-26T00:00:00+00:00, state:running, queued_at: 2024-08-28 09:21:07.630512+00:00. externally triggered: False>
[2024-08-28T09:21:13.770+0000] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near ";"
LINE 4:                 Status varchar(50);
                                          ^
[2024-08-28T09:21:13.770+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=create_table, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240828T092113, end_date=20240828T092113
[2024-08-28T09:21:13.803+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T09:21:13.804+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 91 for task create_table (syntax error at or near ";"
LINE 4:                 Status varchar(50);
                                          ^
; 1453)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near ";"
LINE 4:                 Status varchar(50);
                                          ^

[2024-08-28T09:21:13.864+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T09:21:13.885+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T09:21:13.921+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T09:21:13.926+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-28T09:26:53.249+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T09:26:53.275+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:26:53.287+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [queued]>
[2024-08-28T09:26:53.288+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-28T09:26:53.306+0000] {taskinstance.py:2879} INFO - Executing <Task(PostgresOperator): create_table> on 2024-08-26 00:00:00+00:00
[2024-08-28T09:26:53.313+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1533) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-28T09:26:53.314+0000] {standard_task_runner.py:72} INFO - Started process 1535 to run task
[2024-08-28T09:26:53.315+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_table', 'scheduled__2024-08-26T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/postgres-demo.py', '--cfg-path', '/tmp/tmpqkuo20l5']
[2024-08-28T09:26:53.316+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask create_table
[2024-08-28T09:26:53.375+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator.create_table scheduled__2024-08-26T00:00:00+00:00 [running]> on host 2d2e6ae1efc8
[2024-08-28T09:26:53.478+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='asukhikh' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-26T00:00:00+00:00'
[2024-08-28T09:26:53.479+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-28T09:26:53.480+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-28T09:26:53.480+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2024-08-28 09:26:53.276062+00:00
[2024-08-28T09:26:53.481+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator and current dag run status:running
[2024-08-28T09:26:53.481+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T09:26:53.482+0000] {sql.py:282} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS orders (
                order_id int,
                status varchar(50)
            );
        
[2024-08-28T09:26:53.496+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:26:53.513+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2024-08-28T09:26:53.607+0000] {sql.py:509} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS orders (
                order_id int,
                status varchar(50)
            );
        , parameters: None
[2024-08-28T09:26:53.643+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T09:26:53.643+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator, task_id=create_table, run_id=scheduled__2024-08-26T00:00:00+00:00, execution_date=20240826T000000, start_date=20240828T092653, end_date=20240828T092653
[2024-08-28T09:26:53.656+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-08-28T09:26:53.656+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-08-28T09:26:53.657+0000] {logging_mixin.py:190} INFO - Dag name:dag_with_postgres_operator queued_at:2024-08-28 09:26:46.053615+00:00
[2024-08-28T09:26:53.657+0000] {logging_mixin.py:190} INFO - Task hostname:2d2e6ae1efc8 operator:PostgresOperator
[2024-08-28T09:26:53.692+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-28T09:26:53.716+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-08-28T09:26:53.738+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-28T09:26:53.742+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
